Fix DataParallel aux_loss broadcasting error
When using DataParallel with multiple GPUs, aux_loss from each GPU
is gathered into a vector [aux_loss_gpu0, aux_loss_gpu1, ...].
This caused a broadcasting error when adding to total_loss scalar.

Fix: Average aux_loss when it has multiple values (dim > 0)

Error fixed:
RuntimeError: output with shape [] doesn't match the broadcast shape [2]